version: '3'
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/app
    stdin_open: true #react 종료 시 버그 해결

  db:
    build: ./mysql
    restart: unless-stopped
    container_name: mysql_test
    volumes:
      - ./mysql:/val/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_DATABASE: alexandria

  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    container_name: app_backend
    volumes:
      - /usr/app/node_modules
      - ./server:/app
    restart: always

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
